#!/bin/bash

DOMAIN_NAME=${1}
DOC_ROOT=/var/www

DIR_DOMAIN=$DOC_ROOT/$DOMAIN_NAME

NGINX_HOME=/etc/nginx

SITES_AVAILABLE=$NGINX_HOME/sites-available
SITES_ENABLED=$NGINX_HOME/sites-enabled

mkdir $DIR_DOMAIN
echo "<html><head><title>${1}</title></head><body><center>${1}</center></body></html>" >> $DIR_DOMAIN/index.html

cat  <<EOF>>$SITES_AVAILABLE/$DOMAIN_NAME
server {
    listen       80;
    server_name  $DOMAIN_NAME www.$DOMAIN_NAME;

    location / {
        root   $DIR_DOMAIN;
        index  index.html index.htm;
    }
}
EOF

ln -s $SITES_AVAILABLE/$DOMAIN_NAME $SITES_ENABLED/$DOMAIN_NAME

echo "Domain $DOMAIN_NAME was configured"
