#!/bin/bash

# Shortcuts
# Folders
alias db="cd ${MYHOME}/Dropbox"
alias dl="cd ${MYHOME}/Downloads"
alias dk="cd ${MYHOME}/Desktop"
alias dev="cd ${MYHOME}/_dev"
alias src="cd ${MYHOME}/_dev/src"

if [[ "$OSTYPE" =~ "darwin" ]]; then
	colorflag="-G"
else
	alias pbcopy='xsel --clipboard --input'
	alias pbpaste='xsel --clipboard --output'
	colorflag="--color"
fi

# Commands
alias env="env | sort"
alias ll="ls -l ${colorflag}"
alias lla="ls -l ${colorflag}"
alias ls="command ls ${colorflag}"

alias hist="history"
alias top="top -o cpu"

# Applications
alias vi="vim"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
alias ips="ifconfig -a | grep -o 'inet6\? \(\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)\|[a-fA-F0-9:]\+\)' | sed -e 's/inet6* //'"

# Enhanced WHOIS lookups
alias whois="whois -h whois-servers.net"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

